import "../globals.css";
import type { Metadata } from "next";
import { Inter, Montserrat, Space_Mono } from "next/font/google";
import Header from "./components/layout/header";
import Providers from "./components/providers/providers";
import { Suspense } from "react";
import Footer from "./components/layout/footer";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--inter-font",
});

const montserrat = Montserrat({
	subsets: ["latin"],
	display: "swap",
	variable: "--montserrat-font",
});

const space = Space_Mono({
	style: ["normal", "italic"],
	weight: ["400", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--space-font",
});

export const viewport = {
	width: "device-width",
	initialScale: 1,
};

export const metadata: Metadata = {
	title: "Erik",
	description: "Generated by create next app",
};

const style: React.CSSProperties = {
	colorScheme: "dark",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className='dark' style={style} suppressHydrationWarning>
			<body
				className={`${inter.variable} ${montserrat.variable} ${space.variable} font-body flex-col mx-auto max-w-full min-h-screen`}
			>
				<Providers>
					<Header />
					<Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
